config/routes.rb
Blog::Application.routes.draw do
  resources :posts do
    resources :comments
  end

  resources :users do
    resources :posts
  end
  resources :sessions
  get 'signup' => 'users#new', as: :signup # signup_path
  get 'login' => 'sessions#new', as: :login # login_path
  get 'logout' => 'sessions#destroy', as: :logout # logout_path
    
  root to: 'welcome#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, uniqueness: true, presence: true, length: { minimum: 5 }
  validates :text, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  validates :username, presence: true, uniqueness: true
  # validates :password, presence: true, format: { with: /\A(?=.*[A-Z])(?=.*\d).*\z/ }

  has_secure_password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

protected

  def authorize!
    redirect_to(login_path, notice: 'Log in required.') unless current_user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authorize!
  
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:body).merge(user_id: current_user.id))
    redirect_to post_path(@post)
  end

  def new
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  def edit
  end

  def update
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorize!, except: [:index, :show]
  before_action :get_user, only: :index

  # GET /posts
  # GET /users/:user_id/posts
  def index
    @posts = post_scope.order(created_at: :desc)
  end

  # GET /posts/:id
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
  end

  # CREATE /posts
  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  # GET /posts/:id/edit
  def edit
    @post = current_user.posts.find(params[:id])
  end

  # PATCH /posts/:id
  def update
    @post = current_user.posts.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  # DELETE /posts/:id
  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

private

  def get_user
    @user ||= User.find(params[:user_id]) if params[:user_id]
  end

  def post_scope
    @user ? @user.posts : Post.all
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to posts_path, notice: "Welcome Back #{user.username}!"
    else
      flash.now[:alert] = "We couldn't find that user/password combination."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: 'You are now logged out.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    redirect_to user_posts_path(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to posts_path, notice: "Welcome #{@user.username}! Thanks for signing up!"
    else
      flash.now[:alert] = "There was a problem signing you up."
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_flashes
    flash.collect do |type, message|
      content_tag :div, message, class: "flash flash-#{type}"
    end.join.html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
  <b><%= comment.user.try(:username) || "Anonymous" %>: </b>
  <b>"</b><%= comment.body %>"</b>
</p>
<% if current_user && (@post.user == current_user || comment.user == current_user) %>
<p>
  <%= link_to "Delete Comment", [comment.post, comment], class: "button dark-button small-button", method: :delete, data: { confirm: "If you are certain you would like to delete this comment, click 'OK'." } %>
</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.text_area :body %>
    <%= f.button 'Create Comment', class: 'button dark-button small-button' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class="page-container">
      <%= image_tag 'logo.png', class: 'logo' %>
      <nav>
        <%= link_to "Posts", posts_path, class: 'button' %>
        <%= link_to "Users", users_path, class: 'button' %>
      </nav>
    </div>
  </header>
  <div class="page-container">
    <%= show_flashes %>
    <%= yield %>

    <hr>
    <div class="login">
    <% if current_user %>
    <p>Hi <%= current_user.username %>! <%= link_to 'Logout', logout_path, class: 'button' %></p>
    <% else %>
    <p>Not logged in. <%= link_to 'Login', login_path, class: 'button' %></p>
    <% end %>
    </div>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div id="error explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
      <% @post.errors.full_message.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.button 'Create Post', class: 'button' %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<h1 class="title">Editing post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1 class="title"><%= @user ? "Posts By #{@user.username}" : "All Posts" %></h1>

<table class="posts_list" cellpadding="0" cellspacing="0">
  <tr>
    <th>Title</th>
    <th class="center">Comments</th>
    <% unless @user %><th>Author</th><% end %>
    <th>Text</th>
  </tr>
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td class="center"><%= post.comments.size %></td>
      <% unless @user %><td class="center"><%= post.user.try(:username) || 'Anonymous' %></td><% end %>
      <td><%= post.text %></td>
      <td><%= link_to 'Show', post, class: "button dark-button small-button" %></td>
      <% if current_user && post.user == current_user %>
        <td><%= link_to 'Edit', edit_post_path(post), class: "button dark-button small-button" %></td>
        <td><%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: "If you are certain you would like to delete this post, click 'OK'."  }, class: "button dark-button small-button" %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<%= link_to "Create a New Post", new_post_path, class: "button list_button" %>

app/views/posts/new.html.erb
<h1 class="title">New Post</h1>

<%= render 'form' %>
<br>

app/views/posts/show.html.erb
<p>
  <b class="post_title">Title: "</b>
  <span class="text"><%= @post.title %></span><b class="post_title">"</b>
</p>
<p>
  <b class="post_text">Text: "</b>
  <span class="text"><%= @post.text %></span><b class="post_text">"</b>
</p>

<br><h2 class="comment_header">Comments (<%= @post.comments.size %>) </h2>
<%= render @post.comments %>

<% if current_user %>
<br><h2 class="comment_header">Add A Comment</h2>
<%= render "comments/form" %>
<% end %>

<br><br><br>
<% if @post.user == current_user %>
  <%= link_to "Edit This Post", edit_post_path(@post), class: "button" %>
<% end %>

app/views/users/index.html.erb
<h1 class="title">Users List</h1>

<table class="user_list">
  <tr>
    <th>Username</th>
    <th class="center">ID</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td class="center"><%= user.id %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user, url: users_path do |f| %>
  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/welcome/index.html.erb
<div class="welcome-message">
<h1>Welcome to The Blog</h1>
<p class="special">Where the learning gets tough and the programming gets going.</p>
<aside class="right"><%= image_tag 'blog.jpg' %></aside>
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum.
</p>
</div>